version: "2"

services:
  redis:
    image: redis:latest
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    links:
      - redis
  frontend:
    build: ./multichat_frontend
    command: npm start
    ports:
      - "3000:3000"
